AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CDDemo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./
      Description: 'Lambdafunction for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::332167152351:role/cloud-fromation-service-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /getazs   
            Method: GET
    