AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::332167152351:role/cloud-fromation-service-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/CDDemoLambda-errorlogs/{id}'
            Method: GET
      Environment:
        Variables:
          dbparam: siteiq_database_dev
          dbpasswordparam: siteiq_dbpassword_dev
          dbusernameparam: siteiq_dbusername_dev
          rdshostparam: siteiq_rdshost_dev
