AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CDDemo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./
      Description: 'Lambdafunction for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::332167152351:role/device-data-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path:  '/CDDemoLambda/{id}' 
            Method: GET
      Environment:
        Variables:
          dbparam: siteiq_database_dev
          dbpasswordparam: siteiq_dbpassword_dev
          dbusernameparam: siteiq_dbusername_dev
          rdshostparam: siteiq_rdshost_dev
      Layers:
        - 'arn:aws:lambda:us-east-2:332167152351:layer:pymysql:2'
        - 'arn:aws:lambda:us-east-2:332167152351:layer:crypto:1'
